### PR TITLE
Adjust npm pack spawn for windows. 

### LINKED ISSUE #27: "builder-init builder-react-component" fails on Windows
On my Windows 10 machine with node 5.6.0 & npm 3.6.0...

```
C:\Code> npm -g install builder-init
C:\Users\Stephen\AppData\Roaming\npm\builder-init -> C:\Users\Stephen\AppData\Roaming\npm\node_modules\builder-init\bin\builder-init.js
C:\Users\Stephen\AppData\Roaming\npm
`-- builder-init@0.2.1
```

All seems OK...

```
C:\Code\my-project> builder-init
Usage:

  builder-init [flags] <archetype>

Flags:
...
```

But...

```
C:\Code\my-project> builder-init builder-react-component
Error: spawn npm ENOENT
    at exports._errnoException (util.js:856:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:475:9)
    at process._tickCallback (node.js:389:17)
```

Have I done something wrong?

Kind regards,

Stephen

PS. Builder looks like it could be a serious time saver. Brilliant work!

### PR DESCRIPTION
**Pull request by ryan-roemer**
Ok, this actually seems to be a pretty simple fix. I've manually vetted this against mac and windows. Fixes #27 

@LittleBrainz -- Can you install this branch and confirm it works for you on your Windows machine?

/cc @coopy 

P.S. I've also added #29 to keep Windows CI on our radar.

### CODE REVIEW

**Comment by LittleBrainz** [comment]
@ryan-roemer -- I'm afraid I don't know how to "install this branch".

I originally ran `npm install --save-dev builder builder-react-component builder-react-component-dev`.

Should I manually replace `node_modules/builder/lib/task.js`?

**Comment by ryan-roemer** [comment]
@LittleBrainz -- Sure! Follow these steps:

```sh
$ npm rm -g builder-init
$ npm install -g FormidableLabs/builder-init#bug-windows-spawn
```

After that the original command that you tried:

```sh
$ builder-init builder-react-component
```

Should work with you get prompts to initialize a new project from scratch.

**Comment by LittleBrainz** [comment]
@ryan-roemer -- Yes, everything seems to be working. A big thank you!

Apologies for the strangeness of my last message. I hadn't yet had my morning cup of coffee, so everything I did and said was complete nonsence and gibberish.

Another result! Today I learned that I can NPM install from a GitHub branch. Cool!

**Comment by ryan-roemer** [comment]
Released in `builder-init@0.2.2`

**Pull request merged**
