### PR TITLE
Feature: Add 'archetype' derived data member.

### LINKED ISSUE #18: Feature: Add `archetypePackage` helper variable with the full `package.json` from archetype.
### Goals / Task

* [ ] Make `<archetype>[dev/|]/package.json` available as template data.

### Original Proposal

So that you can do this in `init/package.json`:

```
  "dependencies": {
    "builder": "~2.2.0",
    "builder-react-component": "^<%= archetypePackage.version %>"
  },
  "devDependencies": {
    "builder-react-component-dev": "^<%= archetypePackage.version %>",
    "chai": "^3.2.0",
    "mocha": "^2.3.3",
    "react": "^0.14.0",
    "react-addons-test-utils": "^0.14.0",
    "react-dom": "^0.14.0",
    "sinon": "^1.17.2",
    "sinon-chai": "^2.8.0"
  }
```

This probably obviates the need to implement https://github.com/FormidableLabs/builder-support/issues/7

/cc @chaseadamsio

### PR DESCRIPTION
**Pull request by ryan-roemer**
* Adds `archetype` data member. Fixes #18 
* Add README section on local / `npm link` development of archetypes.

Related PR: https://github.com/FormidableLabs/builder-react-component/pull/36

/cc @chaseadamsio @benbayard @baer @coopy @zachhale @rgerstenberger

### CODE REVIEW

**Comment by rgerstenberger** [comment]
Maybe add a section on automating? like you did here: https://github.com/FormidableLabs/builder-react-component/blob/master/.travis.yml#L40

**Comment by ryan-roemer** [comment]
@rgerstenberger -- It was there previously -- https://github.com/FormidableLabs/builder-init/blob/feature-archetype-data/README.md#automating-prompts  Does that work for you?

**Comment by rgerstenberger** [comment]
Oh, yeah that's awesome! I'd put that in the section on local dev, even just a link to that section would be perfect.

**Comment by ryan-roemer** [comment]
@rgerstenberger -- Rebased a change in here: https://github.com/FormidableLabs/builder-init/pull/20/files#diff-04c6e90faac2675aa89e2176d2eec7d8R478 Look good?

**Comment by rgerstenberger** [comment]
Looks good!

**Comment by ryan-roemer** [comment]
Going cowboy and merging. Post-merge review welcome!!!

**Comment by ryan-roemer** [comment]
Released in `builder-init@0.1.0`

**Pull request merged**
